### ISSUE TITLE
Add Portuguese (PT) Language Support

### ISSUE THREAD

**Issue by oliverulerich** [Lifailon/multranslate#1]
Please add support for Portuguese (PT) language. Currently, the supported languages do not include Portuguese, and it would be useful to have this option.

Thank you.

**Comment by Lifailon** [comment]
> Please add support for Portuguese (PT) language. Currently, the supported languages do not include Portuguese, and it would be useful to have this option.

Hi! Added `pt` parameter:

```
multranslate --language pt
```

or 

```
npm start -- --language pt
```

Example:

![tp](https://github.com/Lifailon/multranslate/blob/rsa/image/issues-1-pt.jpg)

**Comment by Lifailon** [comment]
![Uploading pt.jpg…]()
